const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const canvas=$('#imageCanvas'), overlay=$('#overlayCanvas'), ctx=canvas.getContext('2d',{willReadFrequently:true}), ox=overlay.getContext('2d');
const panelCanvas=$('#panelCanvas'), px=panelCanvas.getContext('2d');
const state={image:null,fileName:'',sourceBitDepth:8,backend:false,measureToken:0,mode:'target',selected:0,groups:{target:[],reference:[]},panelItems:[],drawing:null,drag:null,resize:null,straightenMode:false,straightenLine:null,results:{target:[],reference:[]}};

if(location.protocol.startsWith('http'))fetch('/api/status').then(r=>r.json()).then(x=>{state.backend=!!x.rawBackend;state.backendVersion=x.version||'';renderBackendStatus();renderConnection()}).catch(()=>renderConnection());else renderConnection();
function renderConnection(){const pill=$('#backendPill');pill.classList.toggle('ok',state.backend);pill.classList.toggle('bad',!state.backend);pill.querySelector('span').textContent=state.backend?`原始像素后端 · ${state.backendVersion||'已连接'}`:'预览模式 · 未连接精确后端'}
const welcome=$('#welcomeModal');function openWelcome(){welcome.hidden=false}function closeWelcome(){if($('#welcomeDontShow').checked)localStorage.setItem('wb-hide-welcome','1');welcome.hidden=true}$('#helpBtn').onclick=openWelcome;$('#closeWelcome').onclick=closeWelcome;$('#welcomeStart').onclick=closeWelcome;if(localStorage.getItem('wb-hide-welcome')!=='1')openWelcome();

$('#fileInput').addEventListener('change',e=>importImageFile(e.target.files[0]));
async function importImageFile(f){if(!f)return;if(!/\.(tif|tiff|png|jpe?g)$/i.test(f.name)&&!/^image\//i.test(f.type)){alert('暂不支持该文件。请拖入 TIFF、PNG 或 JPG 图片。');return}try{if(state.backend)await loadBackendImage(f);else if(/\.tiff?$/i.test(f.name)||/tiff/i.test(f.type))await loadTiff(f);else await loadBrowserImage(f)}catch(err){console.error(err);alert('无法读取这张图片：'+(err.message||'未知解码错误'))}}
let dragDepth=0;window.addEventListener('dragenter',e=>{e.preventDefault();dragDepth++;$('#dropOverlay').classList.add('active')});window.addEventListener('dragover',e=>{e.preventDefault();if(e.dataTransfer)e.dataTransfer.dropEffect='copy'});window.addEventListener('dragleave',e=>{e.preventDefault();dragDepth=Math.max(0,dragDepth-1);if(!dragDepth)$('#dropOverlay').classList.remove('active')});window.addEventListener('drop',e=>{e.preventDefault();dragDepth=0;$('#dropOverlay').classList.remove('active');const files=[...(e.dataTransfer?.files||[])],f=files.find(x=>/\.(tif|tiff|png|jpe?g)$/i.test(x.name)||/^image\//i.test(x.type));if(f)importImageFile(f);else alert('没有找到可读取的 TIFF、PNG 或 JPG 图片。')});

function prepareImage(width,height,fileName,bitDepth=8){state.image={width,height};state.fileName=fileName;state.sourceBitDepth=bitDepth;state.groups={target:[],reference:[]};canvas.width=overlay.width=width;canvas.height=overlay.height=height;$('#emptyState').hidden=true;$('#canvasWrap').hidden=false;$('#zoomSelect').value='fit'}
function finishImage(){autoDetectSignal();applyDisplayMode();applyZoom();redraw();calculate()}
function autoDetectSignal(){const d=ctx.getImageData(0,0,canvas.width,canvas.height).data,step=Math.max(4,Math.floor(d.length/20000/4)*4);let sum=0,n=0;for(let i=0;i<d.length;i+=step){sum+=.2126*d[i]+.7152*d[i+1]+.0722*d[i+2];n++}$('#signalMode').value=sum/n<127?'light':'dark'}
function applyDisplayMode(){const choice=$('#displayMode').value,autoInvert=choice==='auto'&&$('#signalMode').value==='light';state.displayInvert=choice==='invert'||autoInvert;canvas.style.filter=state.displayInvert?'invert(1)':'none'}
function loadBrowserImage(file){return new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>{prepareImage(img.naturalWidth,img.naturalHeight,file.name,8);ctx.drawImage(img,0,0);URL.revokeObjectURL(img.src);finishImage();resolve()};img.onerror=()=>reject(new Error('浏览器无法解码该格式'));img.src=URL.createObjectURL(file)})}
async function loadTiff(file){if(typeof UTIF==='undefined')throw new Error('TIFF 解码组件未加载');const buffer=await file.arrayBuffer(),ifds=UTIF.decode(buffer);if(!ifds.length)throw new Error('TIFF 中没有可读取的图像页');const page=ifds[0];UTIF.decodeImage(buffer,page);const width=page.width||page.t256?.[0],height=page.height||page.t257?.[0],bits=page.t258||[8],bitDepth=Math.max(...bits);if(!width||!height)throw new Error('无法识别 TIFF 尺寸');const rgba=UTIF.toRGBA8(page);prepareImage(width,height,file.name,bitDepth);ctx.putImageData(new ImageData(new Uint8ClampedArray(rgba),width,height),0,0);finishImage()}
async function loadBackendImage(file){const res=await fetch('/api/upload',{method:'POST',headers:{'Content-Type':'application/octet-stream','X-Filename':encodeURIComponent(file.name)},body:file}),info=await res.json();if(!res.ok||!info.ok)throw new Error(info.error||'本地读取器上传失败');const img=new Image();await new Promise((resolve,reject)=>{img.onload=resolve;img.onerror=reject;img.src=info.preview+'?t='+Date.now()});prepareImage(info.width,info.height,file.name,8);state.rawBitDepth=info.bits;ctx.drawImage(img,0,0);finishImage();renderBackendStatus(info)}
function renderBackendStatus(info){const badge=$('#qcBadge');if(state.backend&&!state.image)badge.textContent='原始像素后端已连接';if(info)badge.title=`${info.dtype||''} · ${info.bits} bit · ${info.width}×${info.height}`}
$('#modePicker').addEventListener('click',e=>{if(!e.target.dataset.mode)return;state.mode=e.target.dataset.mode;$$('#modePicker button').forEach(b=>b.classList.toggle('active',b.dataset.mode===state.mode));redraw()});
['signalMode','bgGap','bgHeight'].forEach(id=>$('#'+id).addEventListener('change',calculate));
$('#displayMode').addEventListener('change',applyDisplayMode);
$('#signalMode').addEventListener('change',applyDisplayMode);
$('#panelBorder').addEventListener('change',renderPanel);
$('#panelLayout').addEventListener('change',renderPanel);
$('#undoBtn').onclick=()=>{state.groups[state.mode]=[];calculate();redraw()};
$('#clearBtn').onclick=()=>{state.groups={target:[],reference:[]};calculate();redraw()};
$('#removeImageBtn').onclick=()=>{state.image=null;state.fileName='';state.groups={target:[],reference:[]};state.results={target:[],reference:[]};canvas.width=overlay.width=0;canvas.height=overlay.height=0;$('#fileInput').value='';$('#canvasWrap').hidden=true;$('#emptyState').hidden=false;calculate()};
$('#zoomSelect').addEventListener('change',applyZoom);
function applyZoom(){if(!state.image)return;const v=$('#zoomSelect').value;let w=v==='fit'?Math.min(canvas.width,Math.max(320,$('#canvasWrap').clientWidth||900)):Math.round(canvas.width*+v),h=Math.round(w*canvas.height/canvas.width);for(const c of [canvas,overlay]){c.style.width=w+'px';c.style.height=h+'px'}}
$('#focusRoiBtn').onclick=()=>{const r=state.groups[state.mode][0];if(!r){alert('请先关闭“单击放置固定框”，粗略框住整排条带。');return}const wrap=$('#canvasWrap'),scale=clamp(Math.min((wrap.clientWidth*.86)/r.w,(wrap.clientHeight*.72)/r.h),.1,16),w=Math.round(canvas.width*scale),h=Math.round(canvas.height*scale);for(const c of [canvas,overlay]){c.style.width=w+'px';c.style.height=h+'px'}$('#zoomSelect').value='';requestAnimationFrame(()=>{wrap.scrollLeft=(r.x+r.w/2)*scale-wrap.clientWidth/2;wrap.scrollTop=(r.y+r.h/2)*scale-wrap.clientHeight/2})};
$('#straightenBtn').onclick=()=>{if(!state.image){alert('请先导入图片。');return}state.straightenMode=!state.straightenMode;state.straightenLine=null;$('#straightenBtn').classList.toggle('active',state.straightenMode);$('#straightenBtn').textContent=state.straightenMode?'请沿条带拖一条线':'画线拉平';redraw()};
async function applyStraighten(line){const dx=line.end.x-line.start.x,dy=line.end.y-line.start.y;if(Math.hypot(dx,dy)<20){alert('基准线太短，请沿同一排条带画一条更长的线。');return}const radians=Math.atan2(dy,dx),degrees=radians*180/Math.PI;if(Math.abs(degrees)>30){alert('检测到倾斜超过 30°，请沿同一排条带重新画线。');return}if(Math.abs(degrees)<.05){alert('图像已经基本水平，无需校正。');return}if(state.backend){const res=await fetch('/api/rotate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({angle:degrees})}),data=await res.json();if(!res.ok||!data.ok)throw new Error(data.error||'拉平失败');const img=new Image();await new Promise((resolve,reject)=>{img.onload=resolve;img.onerror=reject;img.src=data.preview+'?t='+Date.now()});ctx.clearRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,0,0)}else{const copy=document.createElement('canvas');copy.width=canvas.width;copy.height=canvas.height;copy.getContext('2d').drawImage(canvas,0,0);ctx.save();ctx.clearRect(0,0,canvas.width,canvas.height);ctx.translate(canvas.width/2,canvas.height/2);ctx.rotate(-radians);ctx.drawImage(copy,-copy.width/2,-copy.height/2);ctx.restore()}state.groups={target:[],reference:[]};state.results={target:[],reference:[]};applyDisplayMode();redraw();calculate();alert(`已按基准线校正 ${Math.abs(degrees).toFixed(2)}°。请重新框选 Lane。`)}
$('#detectAllBtn').onclick=()=>detectBands(null);
$('#startRegionBtn').onclick=()=>{$('#fixedPlacement').checked=false;state.groups[state.mode]=[];state.selected=0;redraw();calculate();alert('现在请用鼠标粗略框住一整排目标条带，框内不要包含其他蛋白行。框好后点击“② 识别框内条带”。')};
$('#detectRegionBtn').onclick=()=>{const r=currentRoi();if(!r){alert('请先粗略框住要搜索的条带区域。');return}detectBands(r)};
$('#startFirstLaneBtn').onclick=()=>{$('#fixedPlacement').checked=false;state.groups[state.mode]=[];state.selected=0;redraw();calculate()};
function syncRoiSize(r){if(!r)return;$('#roiWidth').value=Math.round(r.w);$('#roiHeight').value=Math.round(r.h)}
function setRoiSize(r,w,h){const cx=r.x+r.w/2,cy=r.y+r.h/2;r.w=clamp(w,4,canvas.width);r.h=clamp(h,4,canvas.height);r.x=clamp(cx-r.w/2,0,canvas.width-r.w);r.y=clamp(cy-r.h/2,0,canvas.height-r.h)}
$('#applyRoiSizeBtn').onclick=()=>{const r=currentRoi();if(!r){alert('请先框选或选中一个 ROI。');return}setRoiSize(r,+$('#roiWidth').value,+$('#roiHeight').value);calculate();redraw()};
$('#applyAllRoiSizeBtn').onclick=()=>{const g=state.groups[state.mode];if(!g.length){alert('当前没有 ROI。');return}const w=+$('#roiWidth').value,h=+$('#roiHeight').value;g.forEach(r=>setRoiSize(r,w,h));calculate();redraw()};
$('#duplicateLaneBtn').onclick=()=>{const r=currentRoi();if(!r){alert('请先手工框选第1个 Lane。');return}const copy={x:clamp(r.x+r.w*1.5,0,canvas.width-r.w),y:r.y,w:r.w,h:r.h};state.groups[state.mode]=[r,copy];state.selected=1;calculate();redraw()};
$('#generateLanesBtn').onclick=()=>{const g=state.groups[state.mode],n=+$('#manualLaneCount').value;if(g.length<2){alert('需要先框选第1个 Lane，再复制并把第2个框拖到相邻 Lane。');return}const a=g[0],b=g[1],dx=b.x-a.x,dy=b.y-a.y;if(Math.abs(dx)<2){alert('前两个框的水平间距太小，请把第2个框拖到相邻 Lane。');return}const boxes=Array.from({length:n},(_,i)=>({x:a.x+dx*i,y:a.y+dy*i,w:a.w,h:a.h}));if(boxes.some(r=>r.x<0||r.y<0||r.x+r.w>canvas.width||r.y+r.h>canvas.height)){alert('按当前间距生成后会超出图片边界。请调整第1、2个框的位置或减少 Lane 数。');return}state.groups[state.mode]=boxes;state.selected=0;calculate();redraw()};
window.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='d'&&!/INPUT|TEXTAREA/.test(e.target.tagName)){e.preventDefault();$('#duplicateLaneBtn').click()}});
async function detectBands(search){if(!state.backend){alert('自动识别需要通过“启动本地精确版.bat”打开。');return}if(!state.backendVersion){alert('当前后台是旧版本。请关闭黑色的 WB 启动窗口，然后重新双击“启动本地精确版.bat”。');return}const btn=search?$('#detectRegionBtn'):$('#detectAllBtn'),old=btn.textContent;btn.disabled=true;btn.textContent='识别中…';try{const res=await fetch('/api/detect',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({signalMode:$('#signalMode').value,search})}),text=await res.text();let data;try{data=JSON.parse(text)}catch{throw new Error('自动识别后台没有正确响应。请关闭本地服务窗口后重新启动。')}if(!res.ok||!data.ok)throw new Error(data.error||'识别失败');if(!data.boxes.length){alert('没有找到可靠的条带候选。可以先粗框条带区域，再使用“识别当前框内条带”。');return}state.groups[state.mode]=data.boxes;state.selected=0;calculate();redraw();alert(`识别到 ${data.boxes.length} 个候选条带。点击任意绿色框即可选择、移动或加入 Panel。`)}catch(err){alert(err.message)}finally{btn.disabled=false;btn.textContent=old}}
window.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)||/INPUT|SELECT|TEXTAREA/.test(e.target.tagName))return;const r=state.groups[state.mode][0];if(!r)return;e.preventDefault();const d=e.shiftKey?5:1;if(e.key==='ArrowLeft')r.x=clamp(r.x-d,0,canvas.width-r.w);if(e.key==='ArrowRight')r.x=clamp(r.x+d,0,canvas.width-r.w);if(e.key==='ArrowUp')r.y=clamp(r.y-d,0,canvas.height-r.h);if(e.key==='ArrowDown')r.y=clamp(r.y+d,0,canvas.height-r.h);calculate();redraw()});

function pos(e){const r=overlay.getBoundingClientRect();return{x:Math.round((e.clientX-r.left)*overlay.width/r.width),y:Math.round((e.clientY-r.top)*overlay.height/r.height)}}
function hit(p){for(const mode of ['reference','target'])for(let i=state.groups[mode].length-1;i>=0;i--){const r=state.groups[mode][i],h=Math.max(6,Math.min(r.w,r.h)*.25);if(p.x>=r.x+r.w-h&&p.x<=r.x+r.w+h&&p.y>=r.y+r.h-h&&p.y<=r.y+r.h+h)return{mode,i,r,kind:'resize'};if(p.x>=r.x&&p.x<=r.x+r.w&&p.y>=r.y&&p.y<=r.y+r.h)return{mode,i,r,kind:'move'}}return null}
overlay.addEventListener('pointerdown',e=>{if(!state.image)return;const p=pos(e);overlay.setPointerCapture(e.pointerId);if(state.straightenMode){state.straightenLine={start:p,end:p};redraw();return}const h=hit(p);if(h){state.mode=h.mode;state.selected=h.i;syncRoiSize(h.r);$$('#modePicker button').forEach(b=>b.classList.toggle('active',b.dataset.mode===state.mode))}if(h?.kind==='resize')state.resize={...h,start:p,startW:h.r.w,startH:h.r.h};else if(h)state.drag={...h,dx:p.x-h.r.x,dy:p.y-h.r.y};else state.drawing={start:p,end:p}});
overlay.addEventListener('pointermove',e=>{const p=pos(e);if(state.straightenLine){state.straightenLine.end=p;redraw()}else if(state.drawing){state.drawing.end=p;redraw()}else if(state.resize){const r=state.groups[state.resize.mode][state.resize.i];r.w=clamp(state.resize.startW+p.x-state.resize.start.x,4,canvas.width-r.x);r.h=clamp(state.resize.startH+p.y-state.resize.start.y,4,canvas.height-r.y);redraw()}else if(state.drag){const r=state.groups[state.drag.mode][state.drag.i];r.x=clamp(p.x-state.drag.dx,0,canvas.width-r.w);r.y=clamp(p.y-state.drag.dy,0,canvas.height-r.h);redraw()}});
overlay.addEventListener('pointerup',async e=>{if(state.straightenLine){const line={start:state.straightenLine.start,end:pos(e)};state.straightenLine=null;state.straightenMode=false;$('#straightenBtn').classList.remove('active');$('#straightenBtn').textContent='画线拉平';redraw();try{await applyStraighten(line)}catch(err){alert('拉平失败：'+(err?.message||err)+'。如果后台版本过旧，请关闭启动窗口并重新启动工具。')}return}if(state.drawing){const a=state.drawing.start,b=pos(e),r={x:Math.min(a.x,b.x),y:Math.min(a.y,b.y),w:Math.abs(a.x-b.x),h:Math.abs(a.y-b.y)};if(r.w>3&&r.h>3){state.groups[state.mode]=[r];syncRoiSize(r)}state.drawing=null}else{const r=currentRoi();if(r)syncRoiSize(r)}state.drag=null;state.resize=null;calculate();redraw()});

function replicate(r,n){if(n<=1)return[r];const maxStart=canvas.width-r.w, available=maxStart-r.x, step=available/(n-1);return Array.from({length:n},(_,i)=>({...r,x:Math.round(r.x+i*step)}))}
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function redraw(){ox.clearRect(0,0,overlay.width,overlay.height);for(const mode of ['target','reference'])state.groups[mode].forEach((r,i)=>drawRoi(r,i,mode));if(state.drawing){const a=state.drawing.start,b=state.drawing.end;drawOutline({x:Math.min(a.x,b.x),y:Math.min(a.y,b.y),w:Math.abs(a.x-b.x),h:Math.abs(a.y-b.y)},'#ffffff')}if(state.straightenLine){const a=state.straightenLine.start,b=state.straightenLine.end;ox.save();ox.strokeStyle='#ff3b30';ox.lineWidth=3;ox.setLineDash([10,6]);ox.beginPath();ox.moveTo(a.x,a.y);ox.lineTo(b.x,b.y);ox.stroke();ox.setLineDash([]);for(const p of [a,b]){ox.fillStyle='#fff';ox.strokeStyle='#ff3b30';ox.lineWidth=3;ox.beginPath();ox.arc(p.x,p.y,6,0,Math.PI*2);ox.fill();ox.stroke()}ox.restore()}}
function drawRoi(r,i,mode){const selected=mode===state.mode&&i===state.selected,color=selected?'#00f0ff':(mode==='target'?'#20d79a':'#ffb347');drawOutline(r,color);if(selected){ox.strokeStyle='#fff';ox.lineWidth=1;ox.strokeRect(r.x-3,r.y-3,r.w+6,r.h+6)}ox.fillStyle=color;ox.font='bold 12px sans-serif';ox.fillRect(r.x,r.y-18,Math.max(34,ox.measureText(`${mode==='target'?'T':'R'}${i+1}`).width+10),18);ox.fillStyle='#102019';ox.fillText(`${mode==='target'?'T':'R'}${i+1}`,r.x+5,r.y-5);const gap=+$('#bgGap').value,bh=+$('#bgHeight').value;ox.setLineDash([4,3]);for(const y of [r.y-gap-bh,r.y+r.h+gap]){ox.strokeStyle=color;ox.strokeRect(r.x,y,r.w,bh)}ox.setLineDash([])}
function drawOutline(r,color){ox.strokeStyle='#101916';ox.lineWidth=4;ox.strokeRect(r.x,r.y,r.w,r.h);ox.strokeStyle=color;ox.lineWidth=2;ox.strokeRect(r.x,r.y,r.w,r.h);ox.fillStyle=color;ox.fillRect(r.x+r.w-5,r.y+r.h-5,10,10)}

function signalAt(data,i,light){const lum=.2126*data[i]+.7152*data[i+1]+.0722*data[i+2];return light?lum:255-lum}
function pixels(rect,light){const x=clamp(Math.round(rect.x),0,canvas.width-1),y=clamp(Math.round(rect.y),0,canvas.height-1),w=clamp(Math.round(rect.w),1,canvas.width-x),h=clamp(Math.round(rect.h),1,canvas.height-y),d=ctx.getImageData(x,y,w,h).data,a=[];for(let i=0;i<d.length;i+=4)a.push(signalAt(d,i,light));return a}
function median(a){if(!a.length)return 0;const b=[...a].sort((x,y)=>x-y),m=Math.floor(b.length/2);return b.length%2?b[m]:(b[m-1]+b[m])/2}
function measure(r){const light=$('#signalMode').value==='light',gap=+$('#bgGap').value,bh=+$('#bgHeight').value,roi=pixels(r,light),backs=[];if(r.y-gap-bh>=0)backs.push(...pixels({...r,y:r.y-gap-bh,h:bh},light));if(r.y+r.h+gap+bh<=canvas.height)backs.push(...pixels({...r,y:r.y+r.h+gap,h:bh},light));const bg=median(backs),raw=roi.reduce((a,b)=>a+b,0),net=Math.max(0,raw-roi.length*bg),sat=roi.filter(v=>v>=254.5).length/roi.length;return{area:roi.length,rawIntDen:raw,backgroundMedian:bg,netIntDen:net,saturationFraction:sat}}
function calculate(){for(const mode of ['target','reference'])state.results[mode]=state.groups[mode].map(measure);renderOutputs();if(state.backend&&state.image)measureBackend()}
function renderOutputs(){renderTable();renderQc();if(state.backend&&state.image){const li=document.createElement('li');li.className='ok';li.textContent=`✓ 本地原始像素计算已启用（${state.rawBitDepth||8} 位）`;$('#qcList').prepend(li)}renderPanel();const on=state.results.target.length||state.results.reference.length;['exportCsv','exportJson','exportPng'].forEach(id=>$('#'+id).disabled=!on)}
async function measureBackend(){const token=++state.measureToken;try{const res=await fetch('/api/measure',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({groups:state.groups,signalMode:$('#signalMode').value,gap:+$('#bgGap').value,height:+$('#bgHeight').value})}),data=await res.json();if(token!==state.measureToken)return;if(!res.ok||!data.ok)throw new Error(data.error||'原始像素计算失败');state.results=data.results;renderOutputs()}catch(err){console.error(err)}}

function renderPanel(){const mode=$('#panelMode').value,rois=state.groups[mode];if(!state.image||!rois.length){$('#panelPreviewWrap').style.display='none';$('#panelEmpty').style.display='block';$('#exportPanel').disabled=true;return}const base=rois[0],w=Math.max(1,Math.round(base.w)),h=Math.max(1,Math.round(base.h)),gap=+$('#panelGap').value,pad=+$('#panelPad').value,labels=$('#panelLabels').checked,labelH=labels?28:0,totalW=rois.length*w+Math.max(0,rois.length-1)*gap,totalH=h+pad*2+labelH;panelCanvas.width=totalW;panelCanvas.height=totalH;px.fillStyle='#fff';px.fillRect(0,0,totalW,totalH);rois.forEach((r,i)=>{const cx=r.x+r.w/2,cy=r.y+r.h/2,sx=Math.round(cx-w/2),sy=Math.round(cy-h/2-pad),dx=i*(w+gap);const clipX=clamp(sx,0,canvas.width),clipY=clamp(sy,0,canvas.height),clipR=clamp(sx+w,0,canvas.width),clipB=clamp(sy+h+pad*2,0,canvas.height),sw=Math.max(0,clipR-clipX),sh=Math.max(0,clipB-clipY);if(sw&&sh)px.drawImage(canvas,clipX,clipY,sw,sh,dx+(clipX-sx),clipY-sy,sw,sh);if(labels){px.fillStyle='#111';px.font='16px Arial, sans-serif';px.textAlign='center';px.textBaseline='middle';px.fillText(String(i+1),dx+w/2,h+pad*2+labelH/2)}});const lw=+$('#panelLineWidth').value;px.strokeStyle='#111';px.lineWidth=lw;if($('#panelBorder').checked)px.strokeRect(lw/2,lw/2,totalW-lw,totalH-labelH-lw);if($('#panelSeparators').checked)for(let i=1;i<rois.length;i++){const x=i*w+(i-.5)*gap;px.beginPath();px.moveTo(x,0);px.lineTo(x,totalH-labelH);px.stroke()}$('#panelEmpty').style.display='none';$('#panelPreviewWrap').style.display='block';$('#exportPanel').disabled=false}
function fmt(v){return Number.isFinite(v)?v.toLocaleString('zh-CN',{maximumFractionDigits:3}):'—'}
function renderTable(){const t=state.results.target,r=state.results.reference,n=Math.max(t.length,r.length);if(!n){$('#resultBody').innerHTML='<tr><td colspan="6" class="empty-row">框选条带后显示结果</td></tr>';return}const first=t[0]&&r[0]&&r[0].netIntDen?t[0].netIntDen/r[0].netIntDen:null;$('#resultBody').innerHTML=Array.from({length:n},(_,i)=>{const ratio=t[i]&&r[i]&&r[i].netIntDen?t[i].netIntDen/r[i].netIntDen:null,rel=ratio&&first?ratio/first:null,warn=[t[i],r[i]].filter(Boolean).some(x=>x.saturationFraction>.01);return`<tr><td>Lane ${i+1}</td><td>${fmt(t[i]?.netIntDen)}</td><td>${fmt(r[i]?.netIntDen)}</td><td>${fmt(ratio)}</td><td>${fmt(rel)}</td><td>${warn?'⚠ 饱和':'✓'}</td></tr>`}).join('')}
function renderQc(){const all=[...state.results.target,...state.results.reference];if(!state.image){$('#qcBadge').textContent='等待图片';$('#qcList').innerHTML='<li>尚未开始分析</li>';return}const items=[];if(/\.jpe?g$/i.test(state.fileName))items.push(['warn','JPEG 为有损格式，建议换原始 TIFF/PNG']);else items.push(['ok','图片格式适合像素定量']);if(state.sourceBitDepth>8)items.push(['warn',`原图为 ${state.sourceBitDepth} 位；当前浏览器定量按 8 位 RGBA 显示值计算`]);if(!all.length)items.push(['warn','尚未框选条带 ROI']);else{const sat=all.filter(x=>x.saturationFraction>.01).length;items.push(sat?['warn',`${sat} 个 ROI 的饱和信号像素超过 1%`]:['ok','未发现明显的信号饱和']);items.push(['ok','当前组 ROI 尺寸一致']);if(!state.results.reference.length)items.push(['warn','尚未选择内参条带'])}$('#qcList').innerHTML=items.map(([c,s])=>`<li class="${c}">${c==='ok'?'✓':'⚠'} ${s}</li>`).join('');$('#qcBadge').textContent=items.some(x=>x[0]==='warn')?'需要检查':'通过'}

function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
$('#exportCsv').onclick=()=>{const t=state.results.target,r=state.results.reference,n=Math.max(t.length,r.length),rows=[['lane','target_net_int_den','reference_net_int_den','target_reference_ratio','relative_to_lane_1']];const first=t[0]&&r[0]&&r[0].netIntDen?t[0].netIntDen/r[0].netIntDen:null;for(let i=0;i<n;i++){const ratio=t[i]&&r[i]&&r[i].netIntDen?t[i].netIntDen/r[i].netIntDen:'';rows.push([i+1,t[i]?.netIntDen??'',r[i]?.netIntDen??'',ratio,ratio&&first?ratio/first:''])}download(new Blob(['\ufeff'+rows.map(x=>x.join(',')).join('\n')],{type:'text/csv'}),'wb-results.csv')};
$('#exportJson').onclick=()=>download(new Blob([JSON.stringify({version:'0.1.0',source:state.fileName,signalMode:$('#signalMode').value,background:{method:'upper-lower-median',gap:+$('#bgGap').value,height:+$('#bgHeight').value},rois:state.groups,measurements:state.results},null,2)],{type:'application/json'}),'wb-analysis.json');
$('#exportPng').onclick=()=>{const out=document.createElement('canvas');out.width=canvas.width;out.height=canvas.height;const c=out.getContext('2d');c.drawImage(canvas,0,0);c.drawImage(overlay,0,0);out.toBlob(b=>download(b,'wb-annotated.png'))};
function currentRoi(){return state.groups[state.mode][state.selected]||state.groups[state.mode][0]||null}
$('#applyCropSize').onclick=()=>{const r=currentRoi();if(!r){alert('请先在图片上框选一个条带。');return}const w=+$('#cropWidth').value,h=+$('#cropHeight').value,cx=r.x+r.w/2,cy=r.y+r.h/2;r.w=clamp(w,4,canvas.width);r.h=clamp(h,4,canvas.height);r.x=clamp(cx-r.w/2,0,canvas.width-r.w);r.y=clamp(cy-r.h/2,0,canvas.height-r.h);calculate();redraw()};
$('#addToPanel').onclick=()=>{const r=currentRoi();if(!state.image||!r){alert('请先在图片上框选一个条带。');return}const x=Math.round(r.x),y=Math.round(r.y),w=Math.round(r.w),h=Math.round(r.h),crop=document.createElement('canvas');crop.width=w;crop.height=h;crop.getContext('2d').drawImage(canvas,x,y,w,h,0,0,w,h);state.panelItems.push({crop,offset:0,source:state.fileName});renderPanel()};
$('#clearPanel').onclick=()=>{if(state.panelItems.length&&!confirm('确定清空当前 Panel 吗？'))return;state.panelItems=[];renderPanel()};

function renderPanel(){const items=state.panelItems,editor=$('#panelEditor');if(!items.length){editor.style.display='none';editor.innerHTML='';$('#panelPreviewWrap').style.display='none';$('#panelEmpty').style.display='block';$('#exportPanel').disabled=true;return}$('#panelEmpty').style.display='none';editor.style.display='flex';editor.innerHTML='';items.forEach((item,i)=>{const card=document.createElement('div');card.className='panel-item';card.draggable=true;card.dataset.index=i;const img=document.createElement('img');img.src=item.crop.toDataURL('image/png');img.alt=`裁剪 ${i+1}`;const tools=document.createElement('div');tools.className='panel-item-tools';for(const [label,delta] of [['↑',-1],['↓',1]]){const b=document.createElement('button');b.textContent=label;b.className='ghost';b.onclick=e=>{item.offset+=delta*(e.shiftKey?5:1);renderPanel()};tools.appendChild(b)}const del=document.createElement('button');del.textContent='删除';del.className='remove';del.onclick=()=>{items.splice(i,1);renderPanel()};tools.appendChild(del);const off=document.createElement('div');off.className='panel-offset';off.textContent=`顺序 ${i+1} · 垂直 ${item.offset>0?'+':''}${item.offset}px`;card.append(img,tools,off);card.addEventListener('dragstart',()=>card.classList.add('dragging'));card.addEventListener('dragend',()=>card.classList.remove('dragging'));card.addEventListener('dragover',e=>e.preventDefault());card.addEventListener('drop',e=>{e.preventDefault();const from=+editor.querySelector('.dragging')?.dataset.index;if(Number.isNaN(from)||from===i)return;const [moved]=items.splice(from,1);items.splice(i,0,moved);renderPanel()});editor.appendChild(card)});const minOff=Math.min(0,...items.map(x=>x.offset)),top=-minOff,maxBottom=Math.max(...items.map(x=>x.offset+x.crop.height)),height=top+maxBottom,width=items.reduce((s,x)=>s+x.crop.width,0);panelCanvas.width=width;panelCanvas.height=height;px.fillStyle='#fff';px.fillRect(0,0,width,height);let x=0;for(const item of items){px.drawImage(item.crop,x,top+item.offset);x+=item.crop.width}if($('#panelBorder').checked){px.strokeStyle='#111';px.lineWidth=2;px.strokeRect(1,1,width-2,height-2)}$('#panelPreviewWrap').style.display='block';$('#exportPanel').disabled=false}

$('#exportPanel').onclick=()=>panelCanvas.toBlob(b=>download(b,'wb-manual-panel.png'));

function renderPanel(){const items=state.panelItems,editor=$('#panelEditor'),vertical=$('#panelLayout').value==='vertical';if(!items.length){editor.style.display='none';editor.innerHTML='';$('#panelPreviewWrap').style.display='none';$('#panelEmpty').style.display='block';$('#exportPanel').disabled=true;return}$('#panelEmpty').style.display='none';editor.style.display='flex';editor.innerHTML='';items.forEach((item,i)=>{const card=document.createElement('div');card.className='panel-item';card.draggable=true;card.dataset.index=i;const img=document.createElement('img');img.src=item.crop.toDataURL('image/png');img.alt=`裁剪 ${i+1}`;const tools=document.createElement('div');tools.className='panel-item-tools';const moves=vertical?[['←',-1],['→',1]]:[['↑',-1],['↓',1]];for(const [label,delta] of moves){const b=document.createElement('button');b.textContent=label;b.className='ghost';b.onclick=e=>{item.offset+=delta*(e.shiftKey?5:1);renderPanel()};tools.appendChild(b)}const del=document.createElement('button');del.textContent='删除';del.className='remove';del.onclick=()=>{items.splice(i,1);renderPanel()};tools.appendChild(del);const off=document.createElement('div');off.className='panel-offset';off.textContent=`顺序 ${i+1} · ${vertical?'水平':'垂直'} ${item.offset>0?'+':''}${item.offset}px`;card.append(img,tools,off);card.addEventListener('dragstart',()=>card.classList.add('dragging'));card.addEventListener('dragend',()=>card.classList.remove('dragging'));card.addEventListener('dragover',e=>e.preventDefault());card.addEventListener('drop',e=>{e.preventDefault();const dragging=editor.querySelector('.dragging'),from=dragging?+dragging.dataset.index:NaN;if(Number.isNaN(from)||from===i)return;const [moved]=items.splice(from,1);items.splice(i,0,moved);renderPanel()});editor.appendChild(card)});if(vertical){const minOff=Math.min(0,...items.map(x=>x.offset)),left=-minOff,maxRight=Math.max(...items.map(x=>x.offset+x.crop.width)),width=left+maxRight,height=items.reduce((s,x)=>s+x.crop.height,0);panelCanvas.width=width;panelCanvas.height=height;px.fillStyle='#fff';px.fillRect(0,0,width,height);let y=0;for(const item of items){px.drawImage(item.crop,left+item.offset,y);y+=item.crop.height}}else{const minOff=Math.min(0,...items.map(x=>x.offset)),top=-minOff,maxBottom=Math.max(...items.map(x=>x.offset+x.crop.height)),height=top+maxBottom,width=items.reduce((s,x)=>s+x.crop.width,0);panelCanvas.width=width;panelCanvas.height=height;px.fillStyle='#fff';px.fillRect(0,0,width,height);let x=0;for(const item of items){px.drawImage(item.crop,x,top+item.offset);x+=item.crop.width}}if($('#panelBorder').checked){px.strokeStyle='#111';px.lineWidth=2;px.strokeRect(1,1,panelCanvas.width-2,panelCanvas.height-2)}$('#panelPreviewWrap').style.display='block';$('#exportPanel').disabled=false}
