(() => {
  const $=s=>document.querySelector(s);let rows=[],samples=[];
  function ensureSamples(n){if(!samples.length)samples=Array.from({length:n},(_,i)=>`Sample ${i+1}`)}
  function esc(s){s=String(s??'');return /[",\n]/.test(s)?`"${s.replaceAll('"','""')}"`:s}
  function render(){const head=$('#matrixHead'),body=$('#matrixBody');if(!rows.length){head.innerHTML='';body.innerHTML='<tr><td class="empty-row">完成一组 Lane 定量后，将当前灰度加入整膜表</td></tr>';return}head.innerHTML='<tr><th>蛋白名</th>'+samples.map((s,i)=>`<th><input class="matrix-table-input sample-name" data-i="${i}" value="${s}"></th>`).join('')+'<th>操作</th></tr>';body.innerHTML=rows.map((r,ri)=>'<tr><td><input class="matrix-table-input protein-name" data-r="'+ri+'" value="'+r.protein.replaceAll('"','&quot;')+'"></td>'+r.values.map((v,ci)=>`<td><input class="matrix-table-input matrix-value" data-r="${ri}" data-c="${ci}" type="number" step="any" value="${v}"></td>`).join('')+`<td><button class="matrix-delete" data-r="${ri}">删除</button></td></tr>`).join('');head.querySelectorAll('.sample-name').forEach(x=>x.oninput=()=>samples[+x.dataset.i]=x.value);body.querySelectorAll('.protein-name').forEach(x=>x.oninput=()=>rows[+x.dataset.r].protein=x.value);body.querySelectorAll('.matrix-value').forEach(x=>x.oninput=()=>rows[+x.dataset.r].values[+x.dataset.c]=Number(x.value));body.querySelectorAll('.matrix-delete').forEach(x=>x.onclick=()=>{rows.splice(+x.dataset.r,1);render()});$('#exportCsv').disabled=false}
  $('#matrixAdd').onclick=()=>{const current=state.results[state.mode]||[];if(!current.length){alert('当前没有可加入的 Lane 灰度结果。');return}if(rows.length&&current.length!==samples.length){alert(`当前有 ${current.length} 个 Lane，但整膜表为 ${samples.length} 个样本。请保持同一张膜的 Lane 数一致。`);return}ensureSamples(current.length);const protein=$('#matrixProtein').value.trim()||`Protein ${rows.length+1}`;rows.push({protein,values:current.map(x=>x.netIntDen)});$('#matrixProtein').value='';render()};
  $('#matrixClear').onclick=()=>{if(rows.length&&!confirm('确定清空整膜汇总表吗？'))return;rows=[];samples=[];render()};
  $('#exportCsv').onclick=()=>{if(!rows.length){alert('请先把至少一个蛋白加入整膜表。');return}const csv=[['Protein',...samples].map(esc).join(','),...rows.map(r=>[r.protein,...r.values].map(esc).join(','))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}));a.download='wb-membrane-quantification.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
  $('#matrixAdd').addEventListener('click',()=>setTimeout(()=>$('#matrixExport').disabled=!rows.length));
  $('#matrixClear').addEventListener('click',()=>setTimeout(()=>$('#matrixExport').disabled=!rows.length));
  $('#matrixExport').onclick=()=>{if(!rows.length)return;const csv=[['Protein',...samples].map(esc).join(','),...rows.map(r=>[r.protein,...r.values].map(esc).join(','))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}));a.download='wb-membrane-quantification.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
})();
