(() => {
  const W=1000,H=600,stage=new Konva.Stage({container:'studioStage',width:W,height:H}),layer=new Konva.Layer(),tr=new Konva.Transformer({rotateEnabled:false,keepRatio:false,borderStroke:'#176b54',anchorStroke:'#176b54',anchorFill:'#fff'});
  stage.add(layer);layer.add(tr);let selected=[],history=[],historyIndex=-1,restoring=false,idCounter=1;
  const $=s=>document.querySelector(s);
  const quickDelete=document.createElement('button');quickDelete.className='studio-quick-delete';quickDelete.title='删除选中图层';quickDelete.textContent='×';$('#studioStage').appendChild(quickDelete);

  function selectable(){return layer.getChildren(n=>n!==tr)}
  function select(nodes){selected=nodes.filter(Boolean);tr.nodes(selected);layer.draw();renderLayers();positionQuickDelete();syncToneControls();syncFontControl()}
  function positionQuickDelete(){if(selected.length!==1){quickDelete.style.display='none';return}const n=selected[0],rect=n.getClientRect(),content=stage.container().querySelector('.konvajs-content');quickDelete.style.display='block';quickDelete.style.left=(content.offsetLeft+rect.x+rect.width-10)+'px';quickDelete.style.top=(content.offsetTop+rect.y-18)+'px'}
  function nodeName(n){return n.getAttr('layerName')||`${n.getClassName()} ${n.getAttr('studioId')||''}`}
  function bind(n){n.on('dragmove transform',positionQuickDelete);n.on('dragend transformend',()=>{positionQuickDelete();saveHistory()})}
  stage.on('pointerdown',e=>{const target=e.target;if(target===stage){select([]);return}if(target===tr||target.getParent()===tr)return;const multi=e.evt.shiftKey||e.evt.ctrlKey;select(multi?(selected.includes(target)?selected.filter(x=>x!==target):[...selected,target]):[target])});

  function addImage(dataUrl,name,x=30,y=40,attrs={}){return new Promise(resolve=>{const im=new Image();im.onload=()=>{const maxW=700,scale=Math.min(1,maxW/im.width),n=new Konva.Image({image:im,x,y,width:im.width*scale,height:im.height*scale,draggable:true,stroke:'#111',strokeWidth:2,studioId:idCounter++,layerName:name||'条带',sourceData:dataUrl,...attrs});layer.add(n);tr.moveToTop();bind(n);select([n]);layer.draw();resolve(n)};im.src=dataUrl})}
  function addText(text,x=40,y=20,attrs={}){const n=new Konva.Text({text:text||'Protein',x,y,fontSize:24,fontFamily:'Arial',fill:'#111',draggable:true,studioId:idCounter++,layerName:text||'文字',...attrs});layer.add(n);tr.moveToTop();bind(n);select([n]);layer.draw();return n}
  function snapshot(){return selectable().map(n=>{const a={...n.getAttrs()};delete a.image;return{type:n.getClassName(),attrs:a}})}
  function saveHistory(){if(restoring)return;history=history.slice(0,historyIndex+1);history.push(snapshot());if(history.length>50)history.shift();historyIndex=history.length-1;updateUndo()}
  async function restore(data){restoring=true;select([]);selectable().forEach(n=>n.destroy());for(const o of data){if(o.type==='Image')await addImage(o.attrs.sourceData,o.attrs.layerName,o.attrs.x,o.attrs.y,o.attrs);else if(o.type==='Text')addText(o.attrs.text,o.attrs.x,o.attrs.y,o.attrs)}restoring=false;select([]);layer.draw();renderLayers();updateUndo()}
  function updateUndo(){$('#studioUndo').disabled=historyIndex<=0;$('#studioRedo').disabled=historyIndex>=history.length-1}
  function renderLayers(){const box=$('#studioLayers');box.innerHTML='';[...selectable()].reverse().forEach(n=>{const row=document.createElement('div');row.className='studio-layer'+(selected.includes(n)?' active':'');row.innerHTML=`<span>${nodeName(n)}</span><span>${n.getClassName()==='Text'?'T':'▣'}</span>`;row.onclick=e=>select(e.shiftKey?[...selected,n]:[n]);box.appendChild(row)})}
  function selectedImages(){return selected.filter(n=>n.getClassName()==='Image')}
  function syncToneControls(){const imgs=selectedImages(),b=imgs.length?+(imgs[0].getAttr('panelBrightness')||0):0,c=imgs.length?+(imgs[0].getAttr('panelContrast')||0):0;$('#studioBrightness').value=b;$('#studioContrast').value=c;$('#studioBrightnessValue').value=b;$('#studioContrastValue').value=c;$('#studioBrightness').disabled=$('#studioContrast').disabled=!imgs.length}
  function applyTone(){const b=+$('#studioBrightness').value,c=+$('#studioContrast').value;$('#studioBrightnessValue').value=b;$('#studioContrastValue').value=c;selectedImages().forEach(n=>{n.setAttr('panelBrightness',b);n.setAttr('panelContrast',c);n.cache();n.filters([Konva.Filters.Brighten,Konva.Filters.Contrast]);n.brightness(b/100);n.contrast(c)});layer.batchDraw()}
  $('#studioBrightness').oninput=applyTone;$('#studioContrast').oninput=applyTone;
  $('#studioBrightness').onchange=saveHistory;$('#studioContrast').onchange=saveHistory;
  $('#studioResetTone').onclick=()=>{$('#studioBrightness').value=0;$('#studioContrast').value=0;applyTone();saveHistory()};
  function selectedTexts(){return selected.filter(n=>n.getClassName()==='Text')}
  function syncFontControl(){const texts=selectedTexts(),input=$('#studioFontSize'),family=$('#studioFontFamily');input.disabled=family.disabled=!texts.length;if(texts.length){input.value=Math.round(texts[0].fontSize());family.value=texts[0].fontFamily()||'Arial'}}
  $('#studioFontSize').onchange=()=>{const size=Math.max(8,Math.min(96,+$('#studioFontSize').value||24));selectedTexts().forEach(n=>n.fontSize(size));layer.draw();positionQuickDelete();saveHistory()};
  $('#studioFontFamily').onchange=()=>{const family=$('#studioFontFamily').value;selectedTexts().forEach(n=>n.fontFamily(family));layer.draw();positionQuickDelete();saveHistory()};

  $('#studioAddCrop').onclick=async()=>{const r=currentRoi();if(!state.image||!r){alert('请先选择一个条带 ROI。');return}const x=Math.round(r.x),y=Math.round(r.y),w=Math.round(r.w),h=Math.round(r.h),c=document.createElement('canvas');c.width=w;c.height=h;const cropCtx=c.getContext('2d');cropCtx.filter=state.displayInvert?'invert(1)':'none';cropCtx.drawImage(canvas,x,y,w,h,0,0,w,h);const typed=$('#studioName').value.trim(),name=typed||`条带 ${idCounter}`,images=selectable().filter(n=>n.getClassName()==='Image'),last=images.length?images[images.length-1]:null,px=180,py=last?last.y()+last.height()*last.scaleY()+28:60,n=await addImage(c.toDataURL('image/png'),name,px,py);if(typed)addText(name,24,py+Math.max(0,(n.height()-24)/2));saveHistory()};
  $('#studioDelete').onclick=()=>{selected.forEach(n=>n.destroy());select([]);layer.draw();saveHistory()};
  quickDelete.onclick=()=>$('#studioDelete').click();
  $('#studioFront').onclick=()=>{selected.forEach(n=>n.moveUp());tr.moveToTop();layer.draw();saveHistory()};
  $('#studioBack').onclick=()=>{selected.forEach(n=>n.moveDown());tr.moveToTop();layer.draw();saveHistory()};
  $('#studioAlignLeft').onclick=()=>{if(selected.length<2)return;const x=Math.min(...selected.map(n=>n.x()));selected.forEach(n=>n.x(x));layer.draw();saveHistory()};
  $('#studioAlignTop').onclick=()=>{if(selected.length<2)return;const y=Math.min(...selected.map(n=>n.y()));selected.forEach(n=>n.y(y));layer.draw();saveHistory()};
  function distribute(axis){if(selected.length<3)return;const size=axis==='x'?'width':'height',nodes=[...selected].sort((a,b)=>a[axis]()-b[axis]()),start=nodes[0][axis](),end=nodes.at(-1)[axis]()+nodes.at(-1)[size](),total=nodes.reduce((s,n)=>s+n[size](),0),gap=(end-start-total)/(nodes.length-1);let p=start;nodes.forEach(n=>{n[axis](p);p+=n[size]()+gap});layer.draw();saveHistory()}
  $('#studioDistH').onclick=()=>distribute('x');$('#studioDistV').onclick=()=>distribute('y');
  $('#studioUndo').onclick=()=>{if(historyIndex>0)restore(history[--historyIndex])};$('#studioRedo').onclick=()=>{if(historyIndex<history.length-1)restore(history[++historyIndex])};
  window.addEventListener('keydown',e=>{if(/INPUT|TEXTAREA|SELECT/.test(e.target.tagName)||!selected.length)return;if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();const d=e.shiftKey?5:1;selected.forEach(n=>{if(e.key==='ArrowLeft')n.x(n.x()-d);if(e.key==='ArrowRight')n.x(n.x()+d);if(e.key==='ArrowUp')n.y(n.y()-d);if(e.key==='ArrowDown')n.y(n.y()+d)});layer.draw();positionQuickDelete()}if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();$('#studioDelete').click()}});
  window.addEventListener('keyup',e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)&&selected.length)saveHistory()});
  function panelExportData(){select([]);const nodes=selectable();if(!nodes.length){alert('画布中没有可导出的内容。');return null}const rect=layer.getClientRect({skipTransform:false,skipShadow:true,skipStroke:false}),pad=12,x=Math.max(0,rect.x-pad),y=Math.max(0,rect.y-pad),width=Math.min(W-x,rect.width+pad*2),height=Math.min(H-y,rect.height+pad*2),pixelRatio=3,url=stage.toDataURL({x,y,width,height,pixelRatio,mimeType:'image/png'});return{x,y,width,height,pixelRatio,url}}
  $('#studioExport').onclick=()=>{const data=panelExportData();if(!data)return;const a=document.createElement('a');a.href=data.url;a.download='wb-panel-studio.png';a.click()};
  $('#studioExportPdf').onclick=()=>{const data=panelExportData();if(!data)return;if(!window.jspdf?.jsPDF){alert('PDF组件未加载，请强制刷新页面后重试。');return}const dpi=300,pageW=data.width*data.pixelRatio/dpi*72,pageH=data.height*data.pixelRatio/dpi*72,{jsPDF}=window.jspdf,pdf=new jsPDF({orientation:pageW>=pageH?'landscape':'portrait',unit:'pt',format:[pageW,pageH],compress:true});pdf.addImage(data.url,'PNG',0,0,pageW,pageH,undefined,'FAST');pdf.setProperties({title:'WB Panel',subject:'Western blot publication panel',creator:'WB Gray Tool'});pdf.save('wb-panel-studio.pdf')};
  $('#studioSave').onclick=()=>{const blob=new Blob([JSON.stringify({version:1,width:W,height:H,nodes:snapshot()},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='wb-panel-project.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
  $('#studioLoad').onchange=async e=>{try{const p=JSON.parse(await e.target.files[0].text());await restore(p.nodes||[]);saveHistory()}catch(err){alert('工程文件无法读取：'+err.message)}e.target.value=''};
  const cropModal=$('#cropNameModal');
  $('#studioAddCrop').onclick=()=>{if(!state.image||!currentRoi()){alert('请先选择一个条带 ROI。');return}$('#cropNameInput').value=$('#studioName').value.trim();$('#cropFontFamily').value='Arial';cropModal.hidden=false;setTimeout(()=>$('#cropNameInput').focus(),0)};
  $('#cancelCropName').onclick=()=>cropModal.hidden=true;
  cropModal.addEventListener('pointerdown',e=>{if(e.target===cropModal)cropModal.hidden=true});
  async function addNamedCrop(name,fontSize,fontFamily){const r=currentRoi(),x=Math.round(r.x),y=Math.round(r.y),w=Math.round(r.w),h=Math.round(r.h),c=document.createElement('canvas');c.width=w;c.height=h;const cropCtx=c.getContext('2d');cropCtx.filter=state.displayInvert?'invert(1)':'none';cropCtx.drawImage(canvas,x,y,w,h,0,0,w,h);const images=selectable().filter(n=>n.getClassName()==='Image'),last=images.length?images[images.length-1]:null,px=180,py=last?last.y()+last.height()*last.scaleY()+28:60,label=addText(name,24,py+Math.max(0,(h-fontSize)/2),{fontFamily,fontSize,fill:'#111',layerName:`${name} 文字`});let n;try{n=await addImage(c.toDataURL('image/png'),name,px,py)}catch(err){label.destroy();layer.draw();throw err}label.y(py+Math.max(0,(n.height()-fontSize)/2));label.moveToTop();tr.moveToTop();select([n,label]);layer.draw();$('#studioName').value=name;saveHistory()}
  $('#confirmCropName').onclick=async()=>{const name=$('#cropNameInput').value.trim();if(!name){$('#cropNameInput').focus();return}const size=Math.max(8,Math.min(96,+$('#cropFontSize').value||24)),family=$('#cropFontFamily').value||'Arial';cropModal.hidden=true;$('#confirmCropName').disabled=true;try{await addNamedCrop(name,size,family)}catch(err){console.error(err);alert('加入 Panel 失败：'+(err?.message||err))}finally{$('#confirmCropName').disabled=false}};
  $('#cropNameInput').addEventListener('keydown',e=>{if(e.key==='Enter')$('#confirmCropName').click();if(e.key==='Escape')cropModal.hidden=true});
  const textModal=$('#textNameModal');
  $('#studioAddText').onclick=()=>{$('#textNameInput').value=$('#studioName').value.trim();$('#textFontSize').value=$('#studioFontSize').value||24;$('#textFontFamily').value='Arial';textModal.hidden=false;setTimeout(()=>$('#textNameInput').focus(),0)};
  $('#cancelTextName').onclick=()=>textModal.hidden=true;
  textModal.addEventListener('pointerdown',e=>{if(e.target===textModal)textModal.hidden=true});
  $('#confirmTextName').onclick=()=>{const text=$('#textNameInput').value.trim();if(!text){$('#textNameInput').focus();return}const fontSize=Math.max(8,Math.min(96,+$('#textFontSize').value||24)),fontFamily=$('#textFontFamily').value||'Arial',label=addText(text,40,30,{fontFamily,fontSize,fill:'#111',layerName:text});label.moveToTop();tr.moveToTop();select([label]);layer.draw();$('#studioName').value=text;textModal.hidden=true;saveHistory()};
  $('#textNameInput').addEventListener('keydown',e=>{if(e.key==='Enter')$('#confirmTextName').click();if(e.key==='Escape')textModal.hidden=true});
  saveHistory();renderLayers();syncToneControls();syncFontControl();
})();
